name: simplepim-public

type: node

up:
  - node:
      version: v10.16.0
      yarn: true
      packages:
        - .
        # - path/to/other/package

commands:
  # console:
  # server:
  # build:
  test: yarn test
